name: Build

on:
  push:
    branches:
      - main          # ✅ run on main
  pull_request:        # (optional) run on PRs targeting any branch
  
# Needed so the reusable workflow can optionally delete the temp per-OS artifacts it creates.
permissions:
  contents: read
  actions: write

jobs:
  build:
    uses: reactiveui/actions-common/.github/workflows/workflow-common-setup-and-build.yml@main
    with:
      productNamespacePrefix: Akavache
      solutionFile: Akavache.sln
      installWorkloads: true
    secrets:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
